/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsc.typing.game;

import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class PainelJogo extends javax.swing.JPanel {
    
    ArrayList<String> lista = new ArrayList();
    

    private int segundos = 10;
    private int tempoRestante = 0;
    private boolean jogoParado;
    private boolean cronometro = false;

    public void iniciarCronometro() {
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    try {
                        sleep(1000);
                        if (cronometro) {

                            int min = segundos / 60;
                            int seg = segundos % 60;
                            jlTimer.setText(String.format("%02d:%02d", min, seg));
                            segundos--;
                            if (segundos == 0) {
                                cronometro = false;
                                JOptionPane.showMessageDialog(null,
                                        "O tempo acabou!");
                                FramePrincipal frame = FramePrincipal.frameprincipal;
                                frame.MostraRanking();
                            }
                        }
                        System.out.println("Cronometro: " + cronometro);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(PainelJogo.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

        }.start();

    }

    public void novoJogo() {
        jogoParado = false;
        cronometro = true;
        jlTimer.setText("00:00");
        segundos = 60;

    }

    public void iniciaJogo() {
        if (jogoParado) {
            segundos = tempoRestante;
        } else {
            jlTimer.setText("00:00");
            segundos = 60;
        }

        cronometro = true;
        iniciarCronometro();
        jtInformarPalavra.requestFocus();
        jtInformarPalavra.selectAll();
        jlPalavra.setText(lista.get(0));
    }

    public void pausaJogo() {

        cronometro = false;
        jogoParado = true;
        tempoRestante = segundos;
        JOptionPane.showMessageDialog(null, "Jogo pausado, Aperte 'OK' para voltar ao jogo");
        segundos = tempoRestante;
        jogoParado = false;
        cronometro = true;
        jtInformarPalavra.requestFocus();
        jtInformarPalavra.selectAll();
    }

    /**
     * Creates new form PainelJogo
     */
    public PainelJogo() {
      //24 Palavras
        Collections.shuffle(lista);
        lista.add("Gato");
        lista.add("Mouse");
        lista.add("Bolo");
        lista.add("Bola");
        lista.add("Garrafa");
        lista.add("Perfume");       
        lista.add("Impressora");
        lista.add("Smartphone");
        lista.add("Caixa");      
        lista.add("Computador");      
        lista.add("Notebook");       
        lista.add("Televisão");       
        lista.add("Teclado");       
        lista.add("paralelepípido");       
        lista.add("Hexágono");       
        lista.add("Seiscentos");       
        lista.add("Oftalmologista");
        lista.add("Endocrinologista");       
        lista.add("Psoríase");       
        lista.add("Onomatopeia");     
        lista.add("Organela");       
        lista.add("Complexo");        
        lista.add("Esternocleidomastóideo");      
        lista.add("Inconstitucionalissimamente");
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlPalavra = new javax.swing.JLabel();
        jlPontos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlTimer = new javax.swing.JLabel();
        jtInformarPalavra = new javax.swing.JTextField();
        jbIniciar = new javax.swing.JButton();
        jbVerificar = new javax.swing.JButton();
        jbPausar = new javax.swing.JButton();
        jbRanking = new javax.swing.JButton();

        jlPalavra.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jlPalavra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPalavra.setText("Palavra ");

        jlPontos.setFont(new java.awt.Font("Arial", 1, 34)); // NOI18N
        jlPontos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPontos.setText("0");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 34)); // NOI18N
        jLabel3.setText("Pontuação:");

        jlTimer.setFont(new java.awt.Font("Arial", 1, 34)); // NOI18N
        jlTimer.setText("00:00");

        jtInformarPalavra.setFont(new java.awt.Font("Arial", 0, 34)); // NOI18N
        jtInformarPalavra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtInformarPalavra.setText("Escreva sua palavra aqui");
        jtInformarPalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtInformarPalavraActionPerformed(evt);
            }
        });

        jbIniciar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1492649394_start.png"))); // NOI18N
        jbIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIniciarActionPerformed(evt);
            }
        });

        jbVerificar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jbVerificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1492649514_unit-completed.png"))); // NOI18N
        jbVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVerificarActionPerformed(evt);
            }
        });

        jbPausar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbPausar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1492649426_pause.png"))); // NOI18N
        jbPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPausarActionPerformed(evt);
            }
        });

        jbRanking.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbRanking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1492726699_trophy.png"))); // NOI18N
        jbRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRankingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(126, 126, 126)
                        .addComponent(jlPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlTimer))
                    .addComponent(jtInformarPalavra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addComponent(jlPalavra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPausar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbRanking)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbVerificar)
                .addGap(302, 302, 302))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPontos)
                    .addComponent(jLabel3)
                    .addComponent(jlTimer))
                .addGap(92, 92, 92)
                .addComponent(jlPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtInformarPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbVerificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbPausar)
                    .addComponent(jbIniciar)
                    .addComponent(jbRanking))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtInformarPalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtInformarPalavraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtInformarPalavraActionPerformed

    private void jbRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRankingActionPerformed
        FramePrincipal.frameprincipal.MostraRanking();
        
    }//GEN-LAST:event_jbRankingActionPerformed

    private void jbIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIniciarActionPerformed
        iniciaJogo();
    }//GEN-LAST:event_jbIniciarActionPerformed

    private void jbPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPausarActionPerformed
        pausaJogo();

    }//GEN-LAST:event_jbPausarActionPerformed

    private void jbVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerificarActionPerformed
        jtInformarPalavra.requestFocus();
        jtInformarPalavra.setText("");
    }//GEN-LAST:event_jbVerificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbIniciar;
    private javax.swing.JButton jbPausar;
    private javax.swing.JButton jbRanking;
    private javax.swing.JButton jbVerificar;
    private javax.swing.JLabel jlPalavra;
    private javax.swing.JLabel jlPontos;
    private javax.swing.JLabel jlTimer;
    private javax.swing.JTextField jtInformarPalavra;
    // End of variables declaration//GEN-END:variables
}
