/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsc.typing.game;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author Aluno
 */
public class PainelRanking extends javax.swing.JPanel {

    private static ArrayList<Jogador> lista = new ArrayList<>();
    
    
    public PainelRanking() {
        initComponents();
        jtDigitarNome.setText("Informe seu nome");
        jtDigitarNome.requestFocus();
        jtDigitarNome.selectAll();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jtDigitarNome = new javax.swing.JTextField();
        jbConfirmar = new javax.swing.JButton();
        jbVoltarMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaRanking = new javax.swing.JTextArea();

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ranking");

        jtDigitarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDigitarNomeActionPerformed(evt);
            }
        });
        jtDigitarNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtDigitarNomeKeyPressed(evt);
            }
        });

        jbConfirmar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jbConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1493157504_Checkmark.png"))); // NOI18N
        jbConfirmar.setBorder(null);
        jbConfirmar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });
        jbConfirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbConfirmarKeyPressed(evt);
            }
        });

        jbVoltarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.png"))); // NOI18N
        jbVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarMenuActionPerformed(evt);
            }
        });

        jTextAreaRanking.setColumns(20);
        jTextAreaRanking.setRows(5);
        jScrollPane1.setViewportView(jTextAreaRanking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtDigitarNome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbVoltarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235)
                        .addComponent(jbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 301, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtDigitarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbVoltarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtDigitarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDigitarNomeActionPerformed
      
    }//GEN-LAST:event_jtDigitarNomeActionPerformed

    private void jbVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarMenuActionPerformed
     FramePrincipal.frameprincipal.MostraJogo();    }//GEN-LAST:event_jbVoltarMenuActionPerformed

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
        Jogador reg = new Jogador();
        reg.nome = jtDigitarNome.getText();
        lista.add(reg);
        jTextAreaRanking.setText("");
        for (int i = 0; i < lista.size(); i++) {
            jTextAreaRanking.append(lista.get(i).nome+"\n");
        }
        jtDigitarNome.setText("");
        jtDigitarNome.requestFocus();
        
    }//GEN-LAST:event_jbConfirmarActionPerformed

    private void jbConfirmarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbConfirmarKeyPressed
      
    }//GEN-LAST:event_jbConfirmarKeyPressed

    private void jtDigitarNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDigitarNomeKeyPressed
       
           
     
        
    }//GEN-LAST:event_jtDigitarNomeKeyPressed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaRanking;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JButton jbVoltarMenu;
    private javax.swing.JTextField jtDigitarNome;
    // End of variables declaration//GEN-END:variables
}
